### ISSUE TITLE
Tail call optimisation

### ISSUE THREAD

**Issue by lpil** [jonnyarnold/fn#2]
Needs it, clearly.

**Comment by jonnyarnold** [comment]
Perhaps I should get an `if` statement first?

**Comment by lpil** [comment]
Nah, go with function level pattern matching instead

**Comment by jonnyarnold** [comment]
Ruby doesn't support TCO.

**Comment by lpil** [comment]
Actually it does, but it's disabled by default. You can enable it at runtime.

**Comment by jonnyarnold** [comment]
Cool. Why did they disable it?

**Comment by lpil** [comment]
I think it messes with stack traces or something.
